// Curated catalog of popular Ollama models for the one-click model browser.
//
// `name` is the exact tag passed to `ollama pull` (and POST /api/pull). `size`
// is the approximate download size for the default quantization.
//
// The metadata fields (publisher, parameters, context, license) are curated by
// hand from each model's official model card / the Ollama library. They are
// static (no network calls at runtime) and approximate. For installed models
// the browser overlays exact specs from the local /api/show. Update them when
// adding models or when publishers ship new versions.
//
// Keep this list reasonably small and well-maintained rather than exhaustive.

export const MODEL_CATEGORIES = ['General', 'Reasoning', 'Coding', 'Vision', 'Compact']

export const MODEL_CATALOG = [
  // ---------------- General ----------------
  {
    name: 'llama3.2:3b',
    label: 'Llama 3.2 3B',
    category: 'General',
    size: '2.0 GB',
    publisher: 'Meta',
    parameters: '3B',
    context: '128K',
    license: 'Llama 3.2 Community',
    description: "Meta's compact Llama 3.2. Fast, capable general chat that runs well on most machines.",
  },
  {
    name: 'llama3.1:8b',
    label: 'Llama 3.1 8B',
    category: 'General',
    size: '4.7 GB',
    publisher: 'Meta',
    parameters: '8B',
    context: '128K',
    license: 'Llama 3.1 Community',
    description: "Meta's popular 8B. Excellent all-around model for chat, writing, and reasoning.",
  },
  {
    name: 'llama3.3:70b',
    label: 'Llama 3.3 70B',
    category: 'General',
    size: '43 GB',
    publisher: 'Meta',
    parameters: '70B',
    context: '128K',
    license: 'Llama 3.3 Community',
    description: "Meta's flagship 70B. Top-tier quality, but needs a powerful machine and lots of RAM.",
  },
  {
    name: 'gemma3:4b',
    label: 'Gemma 3 4B',
    category: 'General',
    size: '3.3 GB',
    publisher: 'Google',
    parameters: '4B',
    context: '128K',
    license: 'Gemma',
    description: "Google's Gemma 3. Strong reasoning and multilingual ability in a small footprint.",
  },
  {
    name: 'gemma3:12b',
    label: 'Gemma 3 12B',
    category: 'General',
    size: '8.1 GB',
    publisher: 'Google',
    parameters: '12B',
    context: '128K',
    license: 'Gemma',
    description: 'Google Gemma 3, 12B. A great balance of quality and speed for everyday use.',
  },
  {
    name: 'gemma3:27b',
    label: 'Gemma 3 27B',
    category: 'General',
    size: '17 GB',
    publisher: 'Google',
    parameters: '27B',
    context: '128K',
    license: 'Gemma',
    description: 'Google Gemma 3, 27B. High quality for demanding tasks on capable hardware.',
  },
  {
    name: 'qwen2.5:7b',
    label: 'Qwen 2.5 7B',
    category: 'General',
    size: '4.7 GB',
    publisher: 'Alibaba',
    parameters: '7B',
    context: '128K',
    license: 'Apache 2.0',
    description: "Alibaba's Qwen 2.5. Strong multilingual support and instruction following.",
  },
  {
    name: 'qwen2.5:14b',
    label: 'Qwen 2.5 14B',
    category: 'General',
    size: '9.0 GB',
    publisher: 'Alibaba',
    parameters: '14B',
    context: '128K',
    license: 'Apache 2.0',
    description: 'Qwen 2.5 14B. A higher-quality general model with broad knowledge.',
  },
  {
    name: 'mistral:7b',
    label: 'Mistral 7B',
    category: 'General',
    size: '4.1 GB',
    publisher: 'Mistral AI',
    parameters: '7B',
    context: '32K',
    license: 'Apache 2.0',
    description: 'Mistral 7B. Fast and efficient for summarization, Q&A, and everyday tasks.',
  },
  {
    name: 'mistral-nemo:12b',
    label: 'Mistral Nemo 12B',
    category: 'General',
    size: '7.1 GB',
    publisher: 'Mistral AI',
    parameters: '12B',
    context: '128K',
    license: 'Apache 2.0',
    description: 'Mistral Nemo. Larger context window and strong general performance.',
  },
  {
    name: 'mixtral:8x7b',
    label: 'Mixtral 8x7B',
    category: 'General',
    size: '26 GB',
    publisher: 'Mistral AI',
    parameters: '8x7B (MoE)',
    context: '32K',
    license: 'Apache 2.0',
    description: 'Mixtral mixture-of-experts. High quality; activates only part of the model per token.',
  },
  {
    name: 'phi4:14b',
    label: 'Phi-4 14B',
    category: 'General',
    size: '9.1 GB',
    publisher: 'Microsoft',
    parameters: '14B',
    context: '16K',
    license: 'MIT',
    description: "Microsoft's Phi-4. Punches above its weight with strong reasoning for its size.",
  },

  // ---------------- Reasoning ----------------
  {
    name: 'deepseek-r1:1.5b',
    label: 'DeepSeek-R1 1.5B',
    category: 'Reasoning',
    size: '1.1 GB',
    publisher: 'DeepSeek',
    parameters: '1.5B',
    context: '128K',
    license: 'MIT',
    description: 'A tiny distilled reasoning model. Great for math and logic on light hardware.',
  },
  {
    name: 'deepseek-r1:7b',
    label: 'DeepSeek-R1 7B',
    category: 'Reasoning',
    size: '4.7 GB',
    publisher: 'DeepSeek',
    parameters: '7B',
    context: '128K',
    license: 'MIT',
    description: 'Reasoning-focused. Best for math, logic, and step-by-step problem solving.',
  },
  {
    name: 'deepseek-r1:8b',
    label: 'DeepSeek-R1 8B',
    category: 'Reasoning',
    size: '4.9 GB',
    publisher: 'DeepSeek',
    parameters: '8B',
    context: '128K',
    license: 'MIT',
    description: 'Larger R1 distill. Stronger step-by-step reasoning with modest resource needs.',
  },
  {
    name: 'qwq:32b',
    label: 'QwQ 32B',
    category: 'Reasoning',
    size: '20 GB',
    publisher: 'Alibaba',
    parameters: '32B',
    context: '128K',
    license: 'Apache 2.0',
    description: "Qwen's QwQ. Deliberate, deep reasoning for hard logic and math problems.",
  },

  // ---------------- Coding ----------------
  {
    name: 'qwen2.5-coder:1.5b',
    label: 'Qwen2.5-Coder 1.5B',
    category: 'Coding',
    size: '1.0 GB',
    publisher: 'Alibaba',
    parameters: '1.5B',
    context: '32K',
    license: 'Apache 2.0',
    description: 'Tiny coding model. Code completion and small tasks on modest hardware.',
  },
  {
    name: 'qwen2.5-coder:7b',
    label: 'Qwen2.5-Coder 7B',
    category: 'Coding',
    size: '4.7 GB',
    publisher: 'Alibaba',
    parameters: '7B',
    context: '128K',
    license: 'Apache 2.0',
    description: 'A top open coding model. Best for code generation, debugging, and refactoring.',
  },
  {
    name: 'qwen2.5-coder:14b',
    label: 'Qwen2.5-Coder 14B',
    category: 'Coding',
    size: '9.0 GB',
    publisher: 'Alibaba',
    parameters: '14B',
    context: '128K',
    license: 'Apache 2.0',
    description: 'Larger Qwen Coder. Higher-quality code generation and reasoning over code.',
  },
  {
    name: 'codellama:7b',
    label: 'Code Llama 7B',
    category: 'Coding',
    size: '3.8 GB',
    publisher: 'Meta',
    parameters: '7B',
    context: '16K',
    license: 'Llama 2 Community',
    description: "Meta's coding-focused model. Solid code completion and generation.",
  },
  {
    name: 'codegemma:7b',
    label: 'CodeGemma 7B',
    category: 'Coding',
    size: '5.0 GB',
    publisher: 'Google',
    parameters: '7B',
    context: '8K',
    license: 'Gemma',
    description: "Google's CodeGemma. Code completion and generation across many languages.",
  },
  {
    name: 'starcoder2:3b',
    label: 'StarCoder2 3B',
    category: 'Coding',
    size: '1.7 GB',
    publisher: 'BigCode',
    parameters: '3B',
    context: '16K',
    license: 'BigCode OpenRAIL-M',
    description: 'Hugging Face StarCoder2. Lightweight code completion across 600+ languages.',
  },
  {
    name: 'devstral:24b',
    label: 'Devstral 24B',
    category: 'Coding',
    size: '14 GB',
    publisher: 'Mistral AI',
    parameters: '24B',
    context: '128K',
    license: 'Apache 2.0',
    description: "Mistral's coding agent model. Designed for agentic, multi-step coding workflows.",
  },

  // ---------------- Vision ----------------
  {
    name: 'llava:7b',
    label: 'LLaVA 7B',
    category: 'Vision',
    size: '4.7 GB',
    publisher: 'LLaVA project',
    parameters: '7B',
    context: '4K',
    license: 'Apache 2.0',
    description: 'Multimodal model. Analyze and describe images as well as chat.',
  },
  {
    name: 'llava:13b',
    label: 'LLaVA 13B',
    category: 'Vision',
    size: '8.0 GB',
    publisher: 'LLaVA project',
    parameters: '13B',
    context: '4K',
    license: 'Apache 2.0',
    description: 'Larger LLaVA. Better image understanding and richer descriptions.',
  },
  {
    name: 'moondream:1.8b',
    label: 'Moondream 1.8B',
    category: 'Vision',
    size: '1.7 GB',
    publisher: 'Moondream',
    parameters: '1.8B',
    context: '2K',
    license: 'Apache 2.0',
    description: 'Tiny vision model. Fast image description on low-resource hardware.',
  },

  // ---------------- Compact ----------------
  {
    name: 'llama3.2:1b',
    label: 'Llama 3.2 1B',
    category: 'Compact',
    size: '1.3 GB',
    publisher: 'Meta',
    parameters: '1B',
    context: '128K',
    license: 'Llama 3.2 Community',
    description: 'Ultra-light Llama. Runs almost anywhere; good for quick, simple tasks.',
  },
  {
    name: 'gemma3:1b',
    label: 'Gemma 3 1B',
    category: 'Compact',
    size: '0.8 GB',
    publisher: 'Google',
    parameters: '1B',
    context: '32K',
    license: 'Gemma',
    description: 'Very small Google model. Surprisingly coherent for its tiny size.',
  },
  {
    name: 'qwen2.5:0.5b',
    label: 'Qwen 2.5 0.5B',
    category: 'Compact',
    size: '0.4 GB',
    publisher: 'Alibaba',
    parameters: '0.5B',
    context: '32K',
    license: 'Apache 2.0',
    description: 'The smallest general Qwen. Extremely fast for basic tasks and testing.',
  },
  {
    name: 'smollm2:1.7b',
    label: 'SmolLM2 1.7B',
    category: 'Compact',
    size: '1.1 GB',
    publisher: 'Hugging Face',
    parameters: '1.7B',
    context: '8K',
    license: 'Apache 2.0',
    description: 'Compact and efficient. A capable small model for constrained devices.',
  },
]
