// Curated catalog of popular Ollama models for the one-click model browser.
//
// `name` is the exact tag passed to `ollama pull` (and POST /api/pull). `size`
// is the approximate download size for the default quantization.
//
// The metadata fields (publisher, parameters, context, license) are curated by
// hand from each model's official model card / the Ollama library. They are
// static (no network calls at runtime) and approximate. For installed models
// the browser overlays exact specs from the local /api/show. Update them when
// adding models or when publishers ship new versions.
//
// Around 100 of the most popular models are listed; this is a hand-picked
// shortlist, not the entire Ollama library. You can still pull anything by tag.

export const MODEL_CATEGORIES = ['General', 'Reasoning', 'Coding', 'Vision', 'Compact']

export const MODEL_CATALOG = [
  // ---------------- General ----------------
  {
    name: 'llama3.2:3b',
    label: 'Llama 3.2 3B',
    category: 'General',
    size: '2.0 GB',
    publisher: 'Meta',
    parameters: '3B',
    context: '128K',
    license: 'Llama 3.2 Community',
    description: "Meta's compact Llama 3.2. Fast, capable general chat that runs well on most machines.",
  },
  {
    name: 'llama3.1:8b',
    label: 'Llama 3.1 8B',
    category: 'General',
    size: '4.7 GB',
    publisher: 'Meta',
    parameters: '8B',
    context: '128K',
    license: 'Llama 3.1 Community',
    description: "Meta's popular 8B. Excellent all-around model for chat, writing, and reasoning.",
  },
  {
    name: 'llama3.1:70b',
    label: 'Llama 3.1 70B',
    category: 'General',
    size: '43 GB',
    publisher: 'Meta',
    parameters: '70B',
    context: '128K',
    license: 'Llama 3.1 Community',
    description: 'The larger Llama 3.1. High quality for demanding tasks on capable hardware.',
  },
  {
    name: 'llama3.3:70b',
    label: 'Llama 3.3 70B',
    category: 'General',
    size: '43 GB',
    publisher: 'Meta',
    parameters: '70B',
    context: '128K',
    license: 'Llama 3.3 Community',
    description: "Meta's flagship 70B. Top-tier quality, but needs a powerful machine and lots of RAM.",
  },
  {
    name: 'llama3:8b',
    label: 'Llama 3 8B',
    category: 'General',
    size: '4.7 GB',
    publisher: 'Meta',
    parameters: '8B',
    context: '8K',
    license: 'Llama 3 Community',
    description: 'The original Llama 3 8B. Still a strong, well-rounded general model.',
  },
  {
    name: 'llama3:70b',
    label: 'Llama 3 70B',
    category: 'General',
    size: '40 GB',
    publisher: 'Meta',
    parameters: '70B',
    context: '8K',
    license: 'Llama 3 Community',
    description: 'Llama 3 at 70B. High quality, with a smaller context window than 3.1.',
  },
  {
    name: 'llama2:7b',
    label: 'Llama 2 7B',
    category: 'General',
    size: '3.8 GB',
    publisher: 'Meta',
    parameters: '7B',
    context: '4K',
    license: 'Llama 2 Community',
    description: 'The classic Llama 2 7B. Lightweight and widely supported, though now dated.',
  },
  {
    name: 'llama2:13b',
    label: 'Llama 2 13B',
    category: 'General',
    size: '7.4 GB',
    publisher: 'Meta',
    parameters: '13B',
    context: '4K',
    license: 'Llama 2 Community',
    description: 'Llama 2 at 13B. A bit more capable than 7B for general chat.',
  },
  {
    name: 'gemma3:4b',
    label: 'Gemma 3 4B',
    category: 'General',
    size: '3.3 GB',
    publisher: 'Google',
    parameters: '4B',
    context: '128K',
    license: 'Gemma',
    description: "Google's Gemma 3. Strong reasoning and multilingual ability in a small footprint.",
  },
  {
    name: 'gemma3:12b',
    label: 'Gemma 3 12B',
    category: 'General',
    size: '8.1 GB',
    publisher: 'Google',
    parameters: '12B',
    context: '128K',
    license: 'Gemma',
    description: 'Google Gemma 3, 12B. A great balance of quality and speed for everyday use.',
  },
  {
    name: 'gemma3:27b',
    label: 'Gemma 3 27B',
    category: 'General',
    size: '17 GB',
    publisher: 'Google',
    parameters: '27B',
    context: '128K',
    license: 'Gemma',
    description: 'Google Gemma 3, 27B. High quality for demanding tasks on capable hardware.',
  },
  {
    name: 'gemma2:9b',
    label: 'Gemma 2 9B',
    category: 'General',
    size: '5.4 GB',
    publisher: 'Google',
    parameters: '9B',
    context: '8K',
    license: 'Gemma',
    description: 'Gemma 2 at 9B. A reliable, efficient general model from Google.',
  },
  {
    name: 'gemma2:27b',
    label: 'Gemma 2 27B',
    category: 'General',
    size: '16 GB',
    publisher: 'Google',
    parameters: '27B',
    context: '8K',
    license: 'Gemma',
    description: 'Gemma 2 at 27B. Higher quality for tougher tasks on capable hardware.',
  },
  {
    name: 'qwen2.5:3b',
    label: 'Qwen 2.5 3B',
    category: 'General',
    size: '1.9 GB',
    publisher: 'Alibaba',
    parameters: '3B',
    context: '32K',
    license: 'Qwen Research',
    description: 'A compact Qwen 2.5. Quick and capable for everyday tasks on light hardware.',
  },
  {
    name: 'qwen2.5:7b',
    label: 'Qwen 2.5 7B',
    category: 'General',
    size: '4.7 GB',
    publisher: 'Alibaba',
    parameters: '7B',
    context: '128K',
    license: 'Apache 2.0',
    description: "Alibaba's Qwen 2.5. Strong multilingual support and instruction following.",
  },
  {
    name: 'qwen2.5:14b',
    label: 'Qwen 2.5 14B',
    category: 'General',
    size: '9.0 GB',
    publisher: 'Alibaba',
    parameters: '14B',
    context: '128K',
    license: 'Apache 2.0',
    description: 'Qwen 2.5 14B. A higher-quality general model with broad knowledge.',
  },
  {
    name: 'qwen2.5:32b',
    label: 'Qwen 2.5 32B',
    category: 'General',
    size: '20 GB',
    publisher: 'Alibaba',
    parameters: '32B',
    context: '128K',
    license: 'Apache 2.0',
    description: 'Qwen 2.5 32B. Excellent quality for complex tasks on capable hardware.',
  },
  {
    name: 'qwen2.5:72b',
    label: 'Qwen 2.5 72B',
    category: 'General',
    size: '47 GB',
    publisher: 'Alibaba',
    parameters: '72B',
    context: '128K',
    license: 'Qwen',
    description: 'The flagship Qwen 2.5. Top-tier quality; needs a powerful machine.',
  },
  {
    name: 'qwen3:8b',
    label: 'Qwen 3 8B',
    category: 'General',
    size: '5.2 GB',
    publisher: 'Alibaba',
    parameters: '8B',
    context: '128K',
    license: 'Apache 2.0',
    description: 'Qwen 3 at 8B. A strong newer-generation general model with hybrid thinking.',
  },
  {
    name: 'qwen3:14b',
    label: 'Qwen 3 14B',
    category: 'General',
    size: '9.3 GB',
    publisher: 'Alibaba',
    parameters: '14B',
    context: '128K',
    license: 'Apache 2.0',
    description: 'Qwen 3 at 14B. Higher quality general performance with optional reasoning.',
  },
  {
    name: 'qwen3:32b',
    label: 'Qwen 3 32B',
    category: 'General',
    size: '20 GB',
    publisher: 'Alibaba',
    parameters: '32B',
    context: '128K',
    license: 'Apache 2.0',
    description: 'Qwen 3 at 32B. Excellent quality for demanding work on capable hardware.',
  },
  {
    name: 'qwen3:30b-a3b',
    label: 'Qwen 3 30B A3B (MoE)',
    category: 'General',
    size: '19 GB',
    publisher: 'Alibaba',
    parameters: '30B (MoE)',
    context: '128K',
    license: 'Apache 2.0',
    description: 'A mixture-of-experts Qwen 3. Big-model quality with only 3B active per token.',
  },
  {
    name: 'mistral:7b',
    label: 'Mistral 7B',
    category: 'General',
    size: '4.1 GB',
    publisher: 'Mistral AI',
    parameters: '7B',
    context: '32K',
    license: 'Apache 2.0',
    description: 'Mistral 7B. Fast and efficient for summarization, Q&A, and everyday tasks.',
  },
  {
    name: 'mistral-nemo:12b',
    label: 'Mistral Nemo 12B',
    category: 'General',
    size: '7.1 GB',
    publisher: 'Mistral AI',
    parameters: '12B',
    context: '128K',
    license: 'Apache 2.0',
    description: 'Mistral Nemo. Larger context window and strong general performance.',
  },
  {
    name: 'mistral-small:24b',
    label: 'Mistral Small 24B',
    category: 'General',
    size: '14 GB',
    publisher: 'Mistral AI',
    parameters: '24B',
    context: '32K',
    license: 'Apache 2.0',
    description: 'Mistral Small 3. Strong quality at 24B; a great mid-size general model.',
  },
  {
    name: 'mixtral:8x7b',
    label: 'Mixtral 8x7B',
    category: 'General',
    size: '26 GB',
    publisher: 'Mistral AI',
    parameters: '8x7B (MoE)',
    context: '32K',
    license: 'Apache 2.0',
    description: 'Mixtral mixture-of-experts. High quality; activates only part of the model per token.',
  },
  {
    name: 'mixtral:8x22b',
    label: 'Mixtral 8x22B',
    category: 'General',
    size: '80 GB',
    publisher: 'Mistral AI',
    parameters: '8x22B (MoE)',
    context: '64K',
    license: 'Apache 2.0',
    description: 'The large Mixtral MoE. Excellent quality, but very memory-hungry.',
  },
  {
    name: 'phi4:14b',
    label: 'Phi-4 14B',
    category: 'General',
    size: '9.1 GB',
    publisher: 'Microsoft',
    parameters: '14B',
    context: '16K',
    license: 'MIT',
    description: "Microsoft's Phi-4. Punches above its weight with strong reasoning for its size.",
  },
  {
    name: 'phi3:3.8b',
    label: 'Phi-3 Mini 3.8B',
    category: 'General',
    size: '2.2 GB',
    publisher: 'Microsoft',
    parameters: '3.8B',
    context: '128K',
    license: 'MIT',
    description: 'Phi-3 Mini. A small, efficient model with a large context window.',
  },
  {
    name: 'phi3.5:3.8b',
    label: 'Phi-3.5 Mini 3.8B',
    category: 'General',
    size: '2.2 GB',
    publisher: 'Microsoft',
    parameters: '3.8B',
    context: '128K',
    license: 'MIT',
    description: 'Phi-3.5 Mini. An improved small model with strong multilingual ability.',
  },
  {
    name: 'command-r:35b',
    label: 'Command R 35B',
    category: 'General',
    size: '19 GB',
    publisher: 'Cohere',
    parameters: '35B',
    context: '128K',
    license: 'CC-BY-NC 4.0',
    description: "Cohere's Command R. Tuned for retrieval-augmented generation and tool use.",
  },
  {
    name: 'command-r-plus:104b',
    label: 'Command R+ 104B',
    category: 'General',
    size: '59 GB',
    publisher: 'Cohere',
    parameters: '104B',
    context: '128K',
    license: 'CC-BY-NC 4.0',
    description: "Cohere's flagship. Top-tier RAG and tool use; needs serious hardware.",
  },
  {
    name: 'aya:8b',
    label: 'Aya 23 8B',
    category: 'General',
    size: '4.8 GB',
    publisher: 'Cohere',
    parameters: '8B',
    context: '8K',
    license: 'CC-BY-NC 4.0',
    description: "Cohere's Aya. A multilingual model covering 23 languages well.",
  },
  {
    name: 'yi:34b',
    label: 'Yi 34B',
    category: 'General',
    size: '19 GB',
    publisher: '01.AI',
    parameters: '34B',
    context: '4K',
    license: 'Apache 2.0',
    description: "01.AI's Yi 34B. Strong bilingual (English and Chinese) general performance.",
  },
  {
    name: 'solar:10.7b',
    label: 'SOLAR 10.7B',
    category: 'General',
    size: '6.1 GB',
    publisher: 'Upstage',
    parameters: '10.7B',
    context: '4K',
    license: 'CC-BY-NC 4.0',
    description: "Upstage's SOLAR. Punches above its size thanks to depth up-scaling.",
  },
  {
    name: 'granite3.1-dense:8b',
    label: 'Granite 3.1 Dense 8B',
    category: 'General',
    size: '4.9 GB',
    publisher: 'IBM',
    parameters: '8B',
    context: '128K',
    license: 'Apache 2.0',
    description: "IBM's Granite 3.1. Enterprise-focused model with strong tool and RAG support.",
  },
  {
    name: 'hermes3:8b',
    label: 'Hermes 3 8B',
    category: 'General',
    size: '4.7 GB',
    publisher: 'Nous Research',
    parameters: '8B',
    context: '128K',
    license: 'Llama 3.1 Community',
    description: "Nous Research's Hermes 3. A capable, steerable Llama 3.1 fine-tune.",
  },
  {
    name: 'dolphin3:8b',
    label: 'Dolphin 3.0 8B',
    category: 'General',
    size: '4.9 GB',
    publisher: 'Cognitive Computations',
    parameters: '8B',
    context: '128K',
    license: 'Llama 3.1 Community',
    description: 'Dolphin 3.0. An instruction-tuned, steerable general assistant model.',
  },
  {
    name: 'wizardlm2:7b',
    label: 'WizardLM-2 7B',
    category: 'General',
    size: '4.1 GB',
    publisher: 'Microsoft',
    parameters: '7B',
    context: '32K',
    license: 'Apache 2.0',
    description: "Microsoft's WizardLM-2. Strong at complex chat and instruction following.",
  },
  {
    name: 'tulu3:8b',
    label: 'Tulu 3 8B',
    category: 'General',
    size: '4.9 GB',
    publisher: 'Allen AI',
    parameters: '8B',
    context: '128K',
    license: 'Llama 3.1 Community',
    description: "Allen AI's Tulu 3. A well-rounded, openly post-trained instruction model.",
  },

  // ---------------- Reasoning ----------------
  {
    name: 'deepseek-r1:1.5b',
    label: 'DeepSeek-R1 1.5B',
    category: 'Reasoning',
    size: '1.1 GB',
    publisher: 'DeepSeek',
    parameters: '1.5B',
    context: '128K',
    license: 'MIT',
    description: 'A tiny distilled reasoning model. Great for math and logic on light hardware.',
  },
  {
    name: 'deepseek-r1:7b',
    label: 'DeepSeek-R1 7B',
    category: 'Reasoning',
    size: '4.7 GB',
    publisher: 'DeepSeek',
    parameters: '7B',
    context: '128K',
    license: 'MIT',
    description: 'Reasoning-focused. Best for math, logic, and step-by-step problem solving.',
  },
  {
    name: 'deepseek-r1:8b',
    label: 'DeepSeek-R1 8B',
    category: 'Reasoning',
    size: '4.9 GB',
    publisher: 'DeepSeek',
    parameters: '8B',
    context: '128K',
    license: 'MIT',
    description: 'Larger R1 distill. Stronger step-by-step reasoning with modest resource needs.',
  },
  {
    name: 'deepseek-r1:14b',
    label: 'DeepSeek-R1 14B',
    category: 'Reasoning',
    size: '9.0 GB',
    publisher: 'DeepSeek',
    parameters: '14B',
    context: '128K',
    license: 'MIT',
    description: 'A 14B R1 distill. Noticeably deeper reasoning for harder problems.',
  },
  {
    name: 'deepseek-r1:32b',
    label: 'DeepSeek-R1 32B',
    category: 'Reasoning',
    size: '20 GB',
    publisher: 'DeepSeek',
    parameters: '32B',
    context: '128K',
    license: 'MIT',
    description: 'A 32B R1 distill. Excellent reasoning quality on capable hardware.',
  },
  {
    name: 'deepseek-r1:70b',
    label: 'DeepSeek-R1 70B',
    category: 'Reasoning',
    size: '43 GB',
    publisher: 'DeepSeek',
    parameters: '70B',
    context: '128K',
    license: 'MIT',
    description: 'The largest R1 distill. Top reasoning quality; needs a powerful machine.',
  },
  {
    name: 'qwq:32b',
    label: 'QwQ 32B',
    category: 'Reasoning',
    size: '20 GB',
    publisher: 'Alibaba',
    parameters: '32B',
    context: '128K',
    license: 'Apache 2.0',
    description: "Qwen's QwQ. Deliberate, deep reasoning for hard logic and math problems.",
  },
  {
    name: 'openthinker:7b',
    label: 'OpenThinker 7B',
    category: 'Reasoning',
    size: '4.7 GB',
    publisher: 'Open Thoughts',
    parameters: '7B',
    context: '32K',
    license: 'Apache 2.0',
    description: 'An open reasoning model trained on curated reasoning traces.',
  },
  {
    name: 'openthinker:32b',
    label: 'OpenThinker 32B',
    category: 'Reasoning',
    size: '20 GB',
    publisher: 'Open Thoughts',
    parameters: '32B',
    context: '32K',
    license: 'Apache 2.0',
    description: 'The larger OpenThinker. Strong, fully open reasoning on capable hardware.',
  },
  {
    name: 'phi4-reasoning:14b',
    label: 'Phi-4 Reasoning 14B',
    category: 'Reasoning',
    size: '11 GB',
    publisher: 'Microsoft',
    parameters: '14B',
    context: '32K',
    license: 'MIT',
    description: "Microsoft's Phi-4 tuned for reasoning. Strong chain-of-thought for its size.",
  },
  {
    name: 'marco-o1:7b',
    label: 'Marco-o1 7B',
    category: 'Reasoning',
    size: '4.7 GB',
    publisher: 'Alibaba',
    parameters: '7B',
    context: '32K',
    license: 'Apache 2.0',
    description: "Alibaba's Marco-o1. An open o1-style reasoning model for open-ended problems.",
  },
  {
    name: 'exaone-deep:7.8b',
    label: 'EXAONE Deep 7.8B',
    category: 'Reasoning',
    size: '4.8 GB',
    publisher: 'LG AI Research',
    parameters: '7.8B',
    context: '32K',
    license: 'EXAONE AI Model License',
    description: "LG's EXAONE Deep. Reasoning-tuned for math, science, and coding.",
  },

  // ---------------- Coding ----------------
  {
    name: 'qwen2.5-coder:0.5b',
    label: 'Qwen2.5-Coder 0.5B',
    category: 'Coding',
    size: '0.5 GB',
    publisher: 'Alibaba',
    parameters: '0.5B',
    context: '32K',
    license: 'Apache 2.0',
    description: 'The smallest Qwen Coder. Quick code completion on very light hardware.',
  },
  {
    name: 'qwen2.5-coder:1.5b',
    label: 'Qwen2.5-Coder 1.5B',
    category: 'Coding',
    size: '1.0 GB',
    publisher: 'Alibaba',
    parameters: '1.5B',
    context: '32K',
    license: 'Apache 2.0',
    description: 'Tiny coding model. Code completion and small tasks on modest hardware.',
  },
  {
    name: 'qwen2.5-coder:3b',
    label: 'Qwen2.5-Coder 3B',
    category: 'Coding',
    size: '1.9 GB',
    publisher: 'Alibaba',
    parameters: '3B',
    context: '32K',
    license: 'Apache 2.0',
    description: 'A small Qwen Coder. Good code completion with a light footprint.',
  },
  {
    name: 'qwen2.5-coder:7b',
    label: 'Qwen2.5-Coder 7B',
    category: 'Coding',
    size: '4.7 GB',
    publisher: 'Alibaba',
    parameters: '7B',
    context: '128K',
    license: 'Apache 2.0',
    description: 'A top open coding model. Best for code generation, debugging, and refactoring.',
  },
  {
    name: 'qwen2.5-coder:14b',
    label: 'Qwen2.5-Coder 14B',
    category: 'Coding',
    size: '9.0 GB',
    publisher: 'Alibaba',
    parameters: '14B',
    context: '128K',
    license: 'Apache 2.0',
    description: 'Larger Qwen Coder. Higher-quality code generation and reasoning over code.',
  },
  {
    name: 'qwen2.5-coder:32b',
    label: 'Qwen2.5-Coder 32B',
    category: 'Coding',
    size: '20 GB',
    publisher: 'Alibaba',
    parameters: '32B',
    context: '128K',
    license: 'Apache 2.0',
    description: 'The flagship Qwen Coder. State-of-the-art open coding on capable hardware.',
  },
  {
    name: 'codellama:7b',
    label: 'Code Llama 7B',
    category: 'Coding',
    size: '3.8 GB',
    publisher: 'Meta',
    parameters: '7B',
    context: '16K',
    license: 'Llama 2 Community',
    description: "Meta's coding-focused model. Solid code completion and generation.",
  },
  {
    name: 'codellama:13b',
    label: 'Code Llama 13B',
    category: 'Coding',
    size: '7.4 GB',
    publisher: 'Meta',
    parameters: '13B',
    context: '16K',
    license: 'Llama 2 Community',
    description: 'Code Llama at 13B. Better code quality than the 7B.',
  },
  {
    name: 'codellama:34b',
    label: 'Code Llama 34B',
    category: 'Coding',
    size: '19 GB',
    publisher: 'Meta',
    parameters: '34B',
    context: '16K',
    license: 'Llama 2 Community',
    description: 'Code Llama at 34B. Strong code generation for capable hardware.',
  },
  {
    name: 'codellama:70b',
    label: 'Code Llama 70B',
    category: 'Coding',
    size: '39 GB',
    publisher: 'Meta',
    parameters: '70B',
    context: '16K',
    license: 'Llama 2 Community',
    description: 'The largest Code Llama. Top-tier code quality; very memory-hungry.',
  },
  {
    name: 'codegemma:2b',
    label: 'CodeGemma 2B',
    category: 'Coding',
    size: '1.6 GB',
    publisher: 'Google',
    parameters: '2B',
    context: '8K',
    license: 'Gemma',
    description: 'A tiny CodeGemma. Fast fill-in-the-middle code completion.',
  },
  {
    name: 'codegemma:7b',
    label: 'CodeGemma 7B',
    category: 'Coding',
    size: '5.0 GB',
    publisher: 'Google',
    parameters: '7B',
    context: '8K',
    license: 'Gemma',
    description: "Google's CodeGemma. Code completion and generation across many languages.",
  },
  {
    name: 'starcoder2:3b',
    label: 'StarCoder2 3B',
    category: 'Coding',
    size: '1.7 GB',
    publisher: 'BigCode',
    parameters: '3B',
    context: '16K',
    license: 'BigCode OpenRAIL-M',
    description: 'Hugging Face StarCoder2. Lightweight code completion across 600+ languages.',
  },
  {
    name: 'starcoder2:15b',
    label: 'StarCoder2 15B',
    category: 'Coding',
    size: '9.1 GB',
    publisher: 'BigCode',
    parameters: '15B',
    context: '16K',
    license: 'BigCode OpenRAIL-M',
    description: 'The larger StarCoder2. Stronger code completion across many languages.',
  },
  {
    name: 'codestral:22b',
    label: 'Codestral 22B',
    category: 'Coding',
    size: '13 GB',
    publisher: 'Mistral AI',
    parameters: '22B',
    context: '32K',
    license: 'Mistral Non-Production',
    description: "Mistral's Codestral. Excellent code generation and fill-in-the-middle.",
  },
  {
    name: 'devstral:24b',
    label: 'Devstral 24B',
    category: 'Coding',
    size: '14 GB',
    publisher: 'Mistral AI',
    parameters: '24B',
    context: '128K',
    license: 'Apache 2.0',
    description: "Mistral's coding agent model. Designed for agentic, multi-step coding workflows.",
  },
  {
    name: 'deepseek-coder:1.3b',
    label: 'DeepSeek Coder 1.3B',
    category: 'Coding',
    size: '0.8 GB',
    publisher: 'DeepSeek',
    parameters: '1.3B',
    context: '16K',
    license: 'DeepSeek License',
    description: 'A tiny DeepSeek Coder. Fast completion for simple coding tasks.',
  },
  {
    name: 'deepseek-coder:6.7b',
    label: 'DeepSeek Coder 6.7B',
    category: 'Coding',
    size: '3.8 GB',
    publisher: 'DeepSeek',
    parameters: '6.7B',
    context: '16K',
    license: 'DeepSeek License',
    description: 'DeepSeek Coder. A capable, efficient model for code generation.',
  },
  {
    name: 'deepseek-coder-v2:16b',
    label: 'DeepSeek Coder V2 16B',
    category: 'Coding',
    size: '8.9 GB',
    publisher: 'DeepSeek',
    parameters: '16B (MoE)',
    context: '128K',
    license: 'DeepSeek License',
    description: 'A mixture-of-experts coder. Strong code quality with a large context.',
  },
  {
    name: 'granite-code:8b',
    label: 'Granite Code 8B',
    category: 'Coding',
    size: '4.6 GB',
    publisher: 'IBM',
    parameters: '8B',
    context: '128K',
    license: 'Apache 2.0',
    description: "IBM's Granite Code. Built for enterprise software development tasks.",
  },
  {
    name: 'yi-coder:9b',
    label: 'Yi-Coder 9B',
    category: 'Coding',
    size: '5.0 GB',
    publisher: '01.AI',
    parameters: '9B',
    context: '128K',
    license: 'Apache 2.0',
    description: "01.AI's Yi-Coder. Strong coding ability with a large context window.",
  },

  // ---------------- Vision ----------------
  {
    name: 'llama3.2-vision:11b',
    label: 'Llama 3.2 Vision 11B',
    category: 'Vision',
    size: '7.9 GB',
    publisher: 'Meta',
    parameters: '11B',
    context: '128K',
    license: 'Llama 3.2 Community',
    description: "Meta's multimodal Llama. Analyze images and documents alongside chat.",
  },
  {
    name: 'llama3.2-vision:90b',
    label: 'Llama 3.2 Vision 90B',
    category: 'Vision',
    size: '55 GB',
    publisher: 'Meta',
    parameters: '90B',
    context: '128K',
    license: 'Llama 3.2 Community',
    description: 'The large Llama 3.2 Vision. Top-tier image understanding; needs serious hardware.',
  },
  {
    name: 'llava:7b',
    label: 'LLaVA 7B',
    category: 'Vision',
    size: '4.7 GB',
    publisher: 'LLaVA project',
    parameters: '7B',
    context: '4K',
    license: 'Apache 2.0',
    description: 'Multimodal model. Analyze and describe images as well as chat.',
  },
  {
    name: 'llava:13b',
    label: 'LLaVA 13B',
    category: 'Vision',
    size: '8.0 GB',
    publisher: 'LLaVA project',
    parameters: '13B',
    context: '4K',
    license: 'Apache 2.0',
    description: 'Larger LLaVA. Better image understanding and richer descriptions.',
  },
  {
    name: 'llava:34b',
    label: 'LLaVA 34B',
    category: 'Vision',
    size: '20 GB',
    publisher: 'LLaVA project',
    parameters: '34B',
    context: '4K',
    license: 'Apache 2.0',
    description: 'The largest LLaVA. Strong multimodal understanding on capable hardware.',
  },
  {
    name: 'llava-llama3:8b',
    label: 'LLaVA-Llama 3 8B',
    category: 'Vision',
    size: '5.5 GB',
    publisher: 'XTuner',
    parameters: '8B',
    context: '8K',
    license: 'Llama 3 Community',
    description: 'LLaVA on a Llama 3 base. Improved image understanding and chat.',
  },
  {
    name: 'llava-phi3:3.8b',
    label: 'LLaVA-Phi 3 3.8B',
    category: 'Vision',
    size: '2.9 GB',
    publisher: 'XTuner',
    parameters: '3.8B',
    context: '4K',
    license: 'MIT',
    description: 'A small LLaVA on a Phi-3 base. Vision and chat on light hardware.',
  },
  {
    name: 'bakllava:7b',
    label: 'BakLLaVA 7B',
    category: 'Vision',
    size: '4.7 GB',
    publisher: 'SkunkworksAI',
    parameters: '7B',
    context: '4K',
    license: 'Apache 2.0',
    description: 'A Mistral-based multimodal model. Capable image description and chat.',
  },
  {
    name: 'moondream:1.8b',
    label: 'Moondream 1.8B',
    category: 'Vision',
    size: '1.7 GB',
    publisher: 'Moondream',
    parameters: '1.8B',
    context: '2K',
    license: 'Apache 2.0',
    description: 'Tiny vision model. Fast image description on low-resource hardware.',
  },
  {
    name: 'minicpm-v:8b',
    label: 'MiniCPM-V 8B',
    category: 'Vision',
    size: '5.5 GB',
    publisher: 'OpenBMB',
    parameters: '8B',
    context: '32K',
    license: 'MiniCPM Model License',
    description: 'A strong compact multimodal model. Good OCR and image understanding.',
  },
  {
    name: 'qwen2.5vl:7b',
    label: 'Qwen2.5-VL 7B',
    category: 'Vision',
    size: '6.0 GB',
    publisher: 'Alibaba',
    parameters: '7B',
    context: '128K',
    license: 'Qwen',
    description: "Qwen's vision-language model. Strong image, document, and chart understanding.",
  },
  {
    name: 'granite3.2-vision:2b',
    label: 'Granite 3.2 Vision 2B',
    category: 'Vision',
    size: '2.4 GB',
    publisher: 'IBM',
    parameters: '2B',
    context: '128K',
    license: 'Apache 2.0',
    description: "IBM's compact vision model. Tuned for documents, tables, and charts.",
  },

  // ---------------- Compact ----------------
  {
    name: 'llama3.2:1b',
    label: 'Llama 3.2 1B',
    category: 'Compact',
    size: '1.3 GB',
    publisher: 'Meta',
    parameters: '1B',
    context: '128K',
    license: 'Llama 3.2 Community',
    description: 'Ultra-light Llama. Runs almost anywhere; good for quick, simple tasks.',
  },
  {
    name: 'gemma3:1b',
    label: 'Gemma 3 1B',
    category: 'Compact',
    size: '0.8 GB',
    publisher: 'Google',
    parameters: '1B',
    context: '32K',
    license: 'Gemma',
    description: 'Very small Google model. Surprisingly coherent for its tiny size.',
  },
  {
    name: 'gemma2:2b',
    label: 'Gemma 2 2B',
    category: 'Compact',
    size: '1.6 GB',
    publisher: 'Google',
    parameters: '2B',
    context: '8K',
    license: 'Gemma',
    description: 'A small Gemma 2. Efficient and capable for everyday light tasks.',
  },
  {
    name: 'qwen2.5:0.5b',
    label: 'Qwen 2.5 0.5B',
    category: 'Compact',
    size: '0.4 GB',
    publisher: 'Alibaba',
    parameters: '0.5B',
    context: '32K',
    license: 'Apache 2.0',
    description: 'The smallest general Qwen. Extremely fast for basic tasks and testing.',
  },
  {
    name: 'qwen2.5:1.5b',
    label: 'Qwen 2.5 1.5B',
    category: 'Compact',
    size: '1.0 GB',
    publisher: 'Alibaba',
    parameters: '1.5B',
    context: '32K',
    license: 'Apache 2.0',
    description: 'A tiny Qwen 2.5. Quick and usable on very light hardware.',
  },
  {
    name: 'qwen3:0.6b',
    label: 'Qwen 3 0.6B',
    category: 'Compact',
    size: '0.5 GB',
    publisher: 'Alibaba',
    parameters: '0.6B',
    context: '32K',
    license: 'Apache 2.0',
    description: 'The smallest Qwen 3. Extremely fast; good for testing and simple tasks.',
  },
  {
    name: 'qwen3:1.7b',
    label: 'Qwen 3 1.7B',
    category: 'Compact',
    size: '1.4 GB',
    publisher: 'Alibaba',
    parameters: '1.7B',
    context: '32K',
    license: 'Apache 2.0',
    description: 'A small Qwen 3 with optional thinking. Capable for its tiny size.',
  },
  {
    name: 'qwen3:4b',
    label: 'Qwen 3 4B',
    category: 'Compact',
    size: '2.6 GB',
    publisher: 'Alibaba',
    parameters: '4B',
    context: '128K',
    license: 'Apache 2.0',
    description: 'A compact Qwen 3. Strong quality and reasoning for its footprint.',
  },
  {
    name: 'smollm2:360m',
    label: 'SmolLM2 360M',
    category: 'Compact',
    size: '0.3 GB',
    publisher: 'Hugging Face',
    parameters: '360M',
    context: '8K',
    license: 'Apache 2.0',
    description: 'A very tiny model. Runs on almost anything for basic text tasks.',
  },
  {
    name: 'smollm2:1.7b',
    label: 'SmolLM2 1.7B',
    category: 'Compact',
    size: '1.1 GB',
    publisher: 'Hugging Face',
    parameters: '1.7B',
    context: '8K',
    license: 'Apache 2.0',
    description: 'Compact and efficient. A capable small model for constrained devices.',
  },
  {
    name: 'tinyllama:1.1b',
    label: 'TinyLlama 1.1B',
    category: 'Compact',
    size: '0.6 GB',
    publisher: 'TinyLlama',
    parameters: '1.1B',
    context: '2K',
    license: 'Apache 2.0',
    description: 'A tiny Llama-architecture model. Very fast for simple tasks and testing.',
  },
  {
    name: 'phi:2.7b',
    label: 'Phi-2 2.7B',
    category: 'Compact',
    size: '1.6 GB',
    publisher: 'Microsoft',
    parameters: '2.7B',
    context: '2K',
    license: 'MIT',
    description: "Microsoft's Phi-2. A small model that was strong for its size.",
  },
  {
    name: 'stablelm2:1.6b',
    label: 'StableLM 2 1.6B',
    category: 'Compact',
    size: '1.0 GB',
    publisher: 'Stability AI',
    parameters: '1.6B',
    context: '4K',
    license: 'Stability AI Community',
    description: "Stability AI's small model. Multilingual and efficient for light use.",
  },
  {
    name: 'granite3.1-moe:1b',
    label: 'Granite 3.1 MoE 1B',
    category: 'Compact',
    size: '1.4 GB',
    publisher: 'IBM',
    parameters: '1B (MoE)',
    context: '128K',
    license: 'Apache 2.0',
    description: "IBM's tiny mixture-of-experts. Low latency with a large context window.",
  },
  {
    name: 'orca-mini:3b',
    label: 'Orca Mini 3B',
    category: 'Compact',
    size: '2.0 GB',
    publisher: 'Orca Mini',
    parameters: '3B',
    context: '2K',
    license: 'Apache 2.0',
    description: 'A small general assistant model. Lightweight for quick everyday tasks.',
  },
]
